steps:
  # Step 1: Install dependencies
  - name: "node:20"
    entrypoint: npm
    args: ["install"]
    id: "install-dependencies"

  # Step 2: Build Astro static site
  - name: "node:20"
    entrypoint: npm
    args: ["run", "build"]
    id: "build-site"
    waitFor: ["install-dependencies"]
    env:
      # Inject Sanity configuration from substitutions
      - "PUBLIC_SANITY_PROJECT_ID=${_SANITY_PROJECT_ID}"
      - "PUBLIC_SANITY_DATASET=${_SANITY_DATASET}"
      - "SANITY_PROJECT_ID=${_SANITY_PROJECT_ID}"
      - "SANITY_DATASET=${_SANITY_DATASET}"
    secretEnv: ["SANITY_API_READ_TOKEN"]

  # Step 3: Deploy to Google Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "-m" # Multi-threaded for faster uploads
      - "rsync"
      - "-r" # Recursive
      - "-c" # Compare checksums (skip unchanged files)
      - "-d" # Delete files in destination not in source
      - "dist/"
      - "gs://${_BUCKET_NAME}/"
    id: "deploy-to-gcs"
    waitFor: ["build-site"]

  # Step 4: Set cache headers for static assets (images, CSS, JS)
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: bash
    args:
      - "-c"
      - |
        gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" -r "gs://${_BUCKET_NAME}/**/*.{js,css,jpg,jpeg,png,gif,svg,webp,woff,woff2,ttf,eot,ico}" || echo "No static assets found, skipping cache headers"
    id: "set-static-cache"
    waitFor: ["deploy-to-gcs"]

  # Step 5: Set short cache for HTML files
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      - "-m"
      - "setmeta"
      - "-h"
      - "Cache-Control:public, max-age=300, must-revalidate"
      - "-r"
      - "gs://${_BUCKET_NAME}/**/*.html"
    id: "set-html-cache"
    waitFor: ["deploy-to-gcs"]

# Substitution variables (can be set in trigger or via --substitutions flag)
substitutions:
  _BUCKET_NAME: "florizeflowers-website" # Default bucket name - override as needed
  _SANITY_PROJECT_ID: "vm53xzke"
  _SANITY_DATASET: "production"

# Use Secret Manager for sensitive tokens (recommended)
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/florize-sanity-read-token/versions/latest
      env: "SANITY_API_READ_TOKEN"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8 # Use more powerful machine for faster builds

timeout: "900s" # 15 minutes timeout
